M48
; DRILL file {KiCad (6.0.6-33-g9052b063de)} date Sun Aug  7 22:11:38 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-07T22:11:38+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-33-g9052b063de)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.850
%
G90
G05
T1
X128.97Y-80.01
X128.97Y-82.55
X134.97Y-80.01
X134.97Y-82.55
T2
X190.8Y-43.9
X190.8Y-133.9
T0
M30
